/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'Michael' at '04/04/19 22:19' with Gradle 3.1
 *
 * @author Michael, @date 04/04/19 22:19
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
